FrontEnd/FrontEndLibros/FrontEndLibros/Models/ViewModel/AutorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEndLibros.Models.ViewModel
{
    public class AutorViewModel
    {
        public int IdAutorLibro { get; set; }
        public int IdLibro { get; set; }
        [Required]
        [Display(Name = "Nombres")]
        public string Nombres { get; set; }
        [Required]
        [Display(Name = "Apellidos")]
        public string Apellidos { get; set; }
        [Required]
        [Display(Name = "Fecha de nacimiento")]
        public string FechaNacimiento { get; set; }
        [Required]
        [Display(Name = "Ciudad de procedencia")]
        public string CiudadProcedencia { get; set; }
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }
    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Models/ViewModel/CrearLibroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEndLibros.Models.ViewModel
{
    public class CrearLibroViewModel
    {
        public int IdLibro { get; set; }
        [Required]
        [Display(Name = "Título")]
        public string Titulo { get; set; }
        [Required]
        [Display(Name = "Año")]
        public int Año { get; set; }
        [Required]
        [Display(Name = "Género")]
        public int NombreGenero { get; set; }
        [Required]
        [Display(Name = "Número páginas")]
        public int NumeroPaginas { get; set; }
        [Required]
        [Display(Name = "Autores")]
        public List<AutorViewModel> LisAut { get; set; }
    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Models/ViewModel/GenerosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEndLibros.Models.ViewModel
{
    public class GenerosViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Models/ViewModel/LibroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FrontEndLibros.Models.ViewModel;

namespace FrontEndLibros.Models.ViewModel
{
    public class LibroViewModel
    {
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public int Año { get; set; }
        public string NombreGenero { get; set; }
        public int NumeroPaginas { get; set; }
        public List<AutorViewModel> LisAut { get; set; }
    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Models/ViewModel/ResponseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FrontEndLibros.Models.ViewModel;

namespace FrontEndLibros.Models.ViewModel
{
    public class ResponseViewModel
    {
        public string mensaje { get; set; }
        public string Estado { get; set; }
        public string excepcion { get; set; }
        public List<LibroViewModel> response { get; set; }
    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FrontEndLibros.Models.ViewModel;

namespace FrontEndLibros.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using FrontEndLibros.Models.ViewModel;
using Newtonsoft.Json;

namespace FrontEndLibros.Controllers
{
    public class LibrosController : Controller
    {

        // GET: Libros
        public ActionResult Index()
        {
            List<LibroViewModel> Lista = ListarLibros();
            return View(Lista);
        }


        private static List<LibroViewModel> ListarLibros(int Id = 0)
        {
            var urlListar = $"https://localhost:44348/api/libros/ListarLibro?IdLibro={Id}";
            ResponseViewModel responseViewModel = new ResponseViewModel();
            List<LibroViewModel> libroViewModel = new List<LibroViewModel>();
            var request = (HttpWebRequest)WebRequest.Create(urlListar);
            request.Method = "GET";
            request.ContentType = "application/json";
            request.Accept = "application/json";
            try
            {
                ServicePointManager.ServerCertificateValidationCallback = delegate
                (object s, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
                { return true; };
                using (WebResponse response = request.GetResponse())
                {
                    using (Stream strReader = response.GetResponseStream())
                    {
                        if (strReader == null) return libroViewModel;
                        using (StreamReader objReader = new StreamReader(strReader))
                        {
                            string responseBody = objReader.ReadToEnd();
                            responseViewModel = JsonConvert.DeserializeObject<ResponseViewModel>(responseBody);
                            libroViewModel = responseViewModel.response;
                            return libroViewModel;
                        }
                    }
                }
            }
            catch (WebException ex)
            {
                return libroViewModel;
            }
        }


        public ActionResult Nuevo()
        {
            ViewBag.ListaGeneros = ListarGeneros();
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(CrearLibroViewModel Modelo)
        {

            if (ModelState.IsValid)
            {
                ResponseViewModel responseViewModel = new ResponseViewModel();
                List<LibroViewModel> libroViewModel = new List<LibroViewModel>();

                var url = $"https://localhost:44348/api/libros/InsertarLibro";
                var request = (HttpWebRequest)WebRequest.Create(url);
                string json = JsonConvert.SerializeObject(Modelo);
                request.Method = "POST";
                request.ContentType = "application/json";
                request.Accept = "application/json";

                using (var streamWriter = new StreamWriter(request.GetRequestStream()))
                {
                    streamWriter.Write(json);
                    streamWriter.Flush();
                    streamWriter.Close();
                }

                try
                {
                    using (WebResponse response = request.GetResponse())
                    {
                        using (Stream strReader = response.GetResponseStream())
                        {
                            if (strReader == null)  return View(Modelo);
                            using (StreamReader objReader = new StreamReader(strReader))
                            {
                                string responseBody = objReader.ReadToEnd();
                                responseViewModel = JsonConvert.DeserializeObject<ResponseViewModel>(responseBody);
                                return View("/");
                            }
                        }
                    }
                }
                catch (WebException ex)
                {
                    return View(Modelo);
                }
            }
            else
            {
                return View(Modelo);
            }
        }

        public List<GenerosViewModel> ListarGeneros()
        {
            List<GenerosViewModel> Lista = new List<GenerosViewModel>();
            Lista.Add(new GenerosViewModel { Id = 1, Nombre = "Prueba1" });
            Lista.Add(new GenerosViewModel { Id = 2, Nombre = "Prueba2" });
            Lista.Add(new GenerosViewModel { Id = 4, Nombre = "Prueba3" });
            return Lista;
        }

    }
}

FrontEnd/FrontEndLibros/FrontEndLibros/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FrontEnd/FrontEndLibros/FrontEndLibros/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FrontEnd/FrontEndLibros/FrontEndLibros/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="jumbotron">
    @*<h2>Hola Mundo</h2>*@
</div>

FrontEnd/FrontEndLibros/FrontEndLibros/Views/Libros/Index.cshtml
@model List<FrontEndLibros.Models.ViewModel.LibroViewModel>
@{
    ViewBag.Title = "Registro de libros";
}


<div class="row" style="margin-top: 6%;">
    <div class="col-md-12" style="text-align:center;">
        <h2>@ViewBag.Title</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-12" style="text-align:right;padding:5px">
        <a href="~/Libros/Nuevo" class="btn btn-primary">Crear Libro</a>
    </div>
    <div class="col-md-12">
        <div class="jumbotron searchBar-filter">
            <input type="text" id="InputBuscar" onkeyup="liveSearch()" placeholder="Buscar..." class="form-control">
            <table class="table table-responsive" id="TblRegistros">
                @foreach (var item in Model)
                {
                    <tr class="searchBar-option">
                        <td style="padding:33px">
                            <div class="col-md-12">
                                <div class="col-md-3">
                                    <label>Libro: </label>
                                    <i>@item.Titulo</i>
                                </div>
                                <div class="col-md-3">
                                    <label>Año: </label>
                                    <i>@item.Año</i>
                                </div>
                                <div class="col-md-3">
                                    <label>Género: </label>
                                    <i>@item.NombreGenero</i>
                                </div>
                                <div class="col-md-3">
                                    <label>N° Páginas: </label>
                                    <i>@item.NumeroPaginas</i>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="row autores" style="display: @(item.LisAut.Count == 0 ? "none" : "block");">
                                    <div class="col-md-12" style="color: red;font-weight:bold">
                                        <h5>Autores:</h5>
                                    </div>
                                    @foreach (var item2 in item.LisAut)
                                    {
                                        <div class="col-md-6">
                                            <div class="col-md-12">
                                                <label>Nombre: </label>
                                                <i>@item2.Nombres @item2.Apellidos</i>
                                            </div>
                                            <div class="col-md-12">
                                                <label>Fecha Nacimiento: </label>
                                                <i>@( Convert.ToDateTime(item2.FechaNacimiento).ToString("dd/MM/yyyy"))</i>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="col-md-12">
                                                <label>Ciudad procedencia: </label>
                                                <i>@item2.CiudadProcedencia</i>
                                            </div>
                                            <div class="col-md-12">
                                                <label>Email: </label>
                                                <i>@item2.Email</i>
                                            </div>
                                        </div>
                                        <div class="col-md-12" style="display: @(item.LisAut.Count <= 1 ? "none" : "block");">
                                            <hr style="border-top: 1px solid #ad9393 !important;" />
                                        </div>

                                    }
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

FrontEnd/FrontEndLibros/FrontEndLibros/Views/Libros/Nuevo.cshtml
@model FrontEndLibros.Models.ViewModel.CrearLibroViewModel
@{
    ViewBag.Title = "Nuevo Libro";
}

<div class="row" style="margin-top: 6%;">
    <div class="col-md-6">
        <h2>@ViewBag.Title</h2>
    </div>
    <div class="col-md-6" style="text-align:right">
        <a id="btnAgregarAuor" class="btn btn-primary" href="~/Libros/Index">Volver</a>
    </div>
</div>

@using (Html.BeginForm("Nuevo", "Libros", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12" style="margin-top: 2%;">
                @Html.LabelFor(x => x.Titulo)
                @Html.TextBoxFor(x => x.Titulo, "", new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(d => d.Titulo, null, new { @class = "red" })
            </div>
            <div class="col-md-4" style="margin-top: 2%;">
                @Html.LabelFor(x => x.Año)
                @Html.TextBoxFor(x => x.Año, "", new { @class = "form-control input-sm", @type = "number" })
                @Html.ValidationMessageFor(d => d.Año, null, new { @class = "red" })
            </div>
            <div class="col-md-4" style="margin-top: 2%;">
                @Html.LabelFor(x => x.NombreGenero)
                @Html.DropDownListFor(x => x.NombreGenero, new SelectList(ViewBag.ListaGeneros, "Id", "Nombre", "Prueba1"), new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(d => d.NombreGenero, null, new { @class = "red" })
            </div>
            <div class="col-md-4" style="margin-top: 2%;">
                @Html.LabelFor(x => x.NumeroPaginas)
                @Html.TextBoxFor(x => x.NumeroPaginas, "", new { @class = "form-control input-sm", @type = "number" })
                @Html.ValidationMessageFor(d => d.NumeroPaginas, null, new { @class = "red" })
            </div>

            <div class="col-md-12">
                <hr />
                <h4>Autores:</h4>
            </div>
            <div class="col-md-6" style="margin-top: 2%;">
                <label>Nombres:</label>
                <input type="text" name="name" id="InputNombres" class="form-control input-sm" />
            </div>
            <div class="col-md-6" style="margin-top: 2%;">
                <label>Apellidos:</label>
                <input type="text" name="name" id="InputApellidos" class="form-control input-sm" />
            </div>
            <div class="col-md-6" style="margin-top: 2%;">
                <label>Fecha de nacimiento:</label>
                <input type="text" name="name" id="InputFechaNaci" class="form-control input-sm" />
            </div>
            <div class="col-md-6" style="margin-top: 2%;">
                <label>Ciudad de procedencia:</label>
                <input type="text" name="name" id="InputCiudadProc" class="form-control input-sm" />
            </div>
            <div class="col-md-12" style="margin-top: 2%;">
                <label>Email:</label>
                <input type="text" name="name" id="InputEmail" class="form-control input-sm" />
            </div>
            <div class="col-md-12" style="margin-top: 2%;">
                <a id="btnAgregarAuor" class="btn btn-warning">Agregar autor</a>
                @Html.ValidationMessageFor(d => d.LisAut, null, new { @class = "red" })
            </div>
        </div>

    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <input type="submit" name="Guardar" value="Guardar Libro" class="btn btn-success" style="width: 100%;" />
        </div>
    </div>
}

FrontEnd/FrontEndLibros/FrontEndLibros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <link href="~/Content/RegistroLibros.css" rel="stylesheet" />
    <script src="~/Scripts/Buscar.js"></script>


    <script type="text/javascript">
        UseDataTables();
    </script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>